[package]
name = "spada"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pcap-parser = { version = "*", features = ["data"] }
packet = "*"
csv = "*"
rand = "*"
hash32 = "*"
